"""Centralized branding constants — user-facing product identity."""

import os

APP_NAME = "embry0"
API_TITLE = "embry0 API"
# Git author identity for agent-generated commits. Override via env vars so a
# deployment can attribute commits to its own bot identity.
GIT_AUTHOR_NAME = os.environ.get("EMBRY0_GIT_AUTHOR_NAME", "embry0")
GIT_AUTHOR_EMAIL = os.environ.get("EMBRY0_GIT_AUTHOR_EMAIL", "embry0-bot@users.noreply.github.com")
COMMIT_TAG = "via embry0"
PR_ATTRIBUTION = "Automatically generated by embry0."
