"""Centralized branding constants — user-facing product identity."""

APP_NAME = "Legion"
API_TITLE = "Legion API"
GIT_AUTHOR_NAME = "Legion"
GIT_AUTHOR_EMAIL = "legion@getlegion.ai"
COMMIT_TAG = "via Legion"
PR_ATTRIBUTION = "Automatically generated by Legion."
