"""Centralized branding constants — user-facing product identity."""

APP_NAME = "Athanor"
API_TITLE = "Athanor API"
GIT_AUTHOR_NAME = "Athanor"
GIT_AUTHOR_EMAIL = "[removed]"
COMMIT_TAG = "via Athanor"
PR_ATTRIBUTION = "Automatically generated by Athanor."
